export interface SwiftCode {
  nameKo: string
  nameEn: string
  swift: string
  city: string
  category: '국내은행' | '인터넷은행' | '정책·중앙은행' | '외국계은행' | '증권·자산운용' | '기타'
}

export const SWIFT_CODES_KR: SwiftCode[] = [
  // ── 국내 시중은행 ──────────────────────────────────────────────
  { nameKo: 'KB국민은행',     nameEn: 'Kookmin Bank',                              swift: 'CZNBKRSE', city: '서울', category: '국내은행' },
  { nameKo: '신한은행',       nameEn: 'Shinhan Bank',                              swift: 'SHBKKRSE', city: '서울', category: '국내은행' },
  { nameKo: '우리은행',       nameEn: 'Woori Bank',                                swift: 'HVBKKRSE', city: '서울', category: '국내은행' },
  { nameKo: '하나은행',       nameEn: 'KEB Hana Bank',                             swift: 'KOEXKRSE', city: '서울', category: '국내은행' },
  { nameKo: 'IBK기업은행',    nameEn: 'Industrial Bank of Korea',                  swift: 'IBKOKRSE', city: '서울', category: '국내은행' },
  { nameKo: 'NH농협은행',     nameEn: 'Nonghyup Bank',                             swift: 'NACFKRSE', city: '서울', category: '국내은행' },
  { nameKo: 'SC제일은행',     nameEn: 'Standard Chartered Bank Korea',             swift: 'SCBLKRSE', city: '서울', category: '국내은행' },
  { nameKo: '씨티은행',       nameEn: 'Citibank Korea',                            swift: 'CITIKRSX', city: '서울', category: '국내은행' },
  { nameKo: 'iM뱅크 (구 대구은행)', nameEn: 'IM Bank (formerly Daegu Bank)',       swift: 'DAEBKR22', city: '대구', category: '국내은행' },
  { nameKo: 'BNK부산은행',    nameEn: 'Busan Bank',                                swift: 'PUSBKR2P', city: '부산', category: '국내은행' },
  { nameKo: '광주은행',       nameEn: 'Kwangju Bank',                              swift: 'KWABKRSE', city: '광주', category: '국내은행' },
  { nameKo: '제주은행',       nameEn: 'Jeju Bank',                                 swift: 'JJBKKR22', city: '제주', category: '국내은행' },
  { nameKo: 'BNK경남은행',    nameEn: 'Kyongnam Bank',                             swift: 'KYNAKR22', city: '창원', category: '국내은행' },
  { nameKo: '전북은행',       nameEn: 'Jeonbuk Bank',                              swift: 'JEONKRSE', city: '서울', category: '국내은행' },
  { nameKo: '수협은행',       nameEn: 'Suhyup Bank',                               swift: 'NFFCKRSE', city: '서울', category: '국내은행' },
  { nameKo: '새마을금고',     nameEn: 'MG Community Credit Cooperatives',          swift: 'MGCCKRSE', city: '서울', category: '국내은행' },
  { nameKo: '신협',           nameEn: 'National Credit Union Federation of Korea', swift: 'NACUKRSE', city: '서울', category: '국내은행' },
  { nameKo: '우체국',         nameEn: 'Korea Post',                                swift: 'SHBKKRSEKPO', city: '서울', category: '국내은행' },
  // ── 인터넷전문은행 ────────────────────────────────────────────
  { nameKo: '케이뱅크',   nameEn: 'K Bank',      swift: 'KBANKRSE', city: '서울', category: '인터넷은행' },
  { nameKo: '카카오뱅크', nameEn: 'Kakaobank',   swift: 'KAKOKR22', city: '성남', category: '인터넷은행' },
  { nameKo: '토스뱅크',   nameEn: 'Toss Bank',   swift: 'TOBNKRSE', city: '서울', category: '인터넷은행' },
  // ── 정책·중앙은행 ────────────────────────────────────────────
  { nameKo: '한국은행',         nameEn: 'Bank of Korea',                  swift: 'BOKRKRSE', city: '서울', category: '정책·중앙은행' },
  { nameKo: '한국은행 (송금)',   nameEn: 'Bank of Korea (Transfer)',        swift: 'BOKRKRST', city: '서울', category: '정책·중앙은행' },
  { nameKo: '한국은행 (결제)',   nameEn: 'Bank of Korea (Payment)',         swift: 'BOKRKRSP', city: '서울', category: '정책·중앙은행' },
  { nameKo: 'KDB산업은행',      nameEn: 'Korea Development Bank',          swift: 'KODBKRSE', city: '서울', category: '정책·중앙은행' },
  { nameKo: '한국수출입은행',   nameEn: 'Export-Import Bank of Korea',     swift: 'EXIKKRSE', city: '서울', category: '정책·중앙은행' },
  // ── 외국계 은행 한국지점 ──────────────────────────────────────
  { nameKo: '중국농업은행 서울지점',       nameEn: 'Agricultural Bank of China Seoul Branch',           swift: 'ABOCKRSE', city: '서울', category: '외국계은행' },
  { nameKo: 'ANZ은행 서울지점',            nameEn: 'Australia and New Zealand Banking Group',           swift: 'ANZBKRSX', city: '서울', category: '외국계은행' },
  { nameKo: '뱅크멜라트 서울지점',         nameEn: 'Bank Mellat Seoul Branch',                          swift: 'BKMTKRS1', city: '서울', category: '외국계은행' },
  { nameKo: '인도네시아국립은행 서울지점', nameEn: 'Bank Negara Indonesia Seoul Branch',                swift: 'BNINKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '뱅크오브아메리카 서울지점',   nameEn: 'Bank of America N.A. Seoul Branch',                 swift: 'BOFAKR2X', city: '서울', category: '외국계은행' },
  { nameKo: '중국은행 서울지점',           nameEn: 'Bank of China Seoul Branch',                        swift: 'BKCHKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '교통은행 서울지점',           nameEn: 'Bank of Communications Seoul Branch',               swift: 'COMMKRSE', city: '서울', category: '외국계은행' },
  { nameKo: 'BNP파리바 서울지점',          nameEn: 'BNP Paribas Seoul Branch',                          swift: 'BNPAKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '중국건설은행 서울지점',       nameEn: 'China Construction Bank Seoul Branch',              swift: 'PCBCKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '중국광대은행 서울지점',       nameEn: 'China Everbright Bank Seoul Branch',                swift: 'EVERKRSE', city: '서울', category: '외국계은행' },
  { nameKo: 'DBS은행 서울지점',            nameEn: 'DBS Bank Seoul Branch',                             swift: 'DBSSKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '도이체방크 서울지점',         nameEn: 'Deutsche Bank AG Seoul Branch',                     swift: 'DEUTKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '골드만삭스 서울지점',         nameEn: 'Goldman Sachs (Asia) L.L.C. Seoul Branch',          swift: 'GSALKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '중국공상은행 서울지점',       nameEn: 'Industrial and Commercial Bank of China Seoul Branch', swift: 'ICBKKRSE', city: '서울', category: '외국계은행' },
  { nameKo: 'ING은행 서울지점',            nameEn: 'ING Bank N.V. Seoul Branch',                        swift: 'INGBKRSE', city: '서울', category: '외국계은행' },
  { nameKo: 'JP모간체이스은행 서울지점',   nameEn: 'JPMorgan Chase Bank N.A. Seoul Branch',             swift: 'CHASKRSX', city: '서울', category: '외국계은행' },
  { nameKo: 'LBBW 서울지점',               nameEn: 'Landesbank Baden-Wuerttemberg Seoul Branch',        swift: 'SOLAKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '로이즈은행 서울지점',         nameEn: 'Lloyds Bank PLC Seoul Branch',                      swift: 'LOYDKRS1', city: '서울', category: '외국계은행' },
  { nameKo: '맥쿼리증권코리아',            nameEn: 'Macquarie Securities Korea Limited',                swift: 'BSKLKRS1', city: '서울', category: '외국계은행' },
  { nameKo: '메트로폴리탄은행 서울지점',   nameEn: 'Metropolitan Bank and Trust Company Seoul',         swift: 'MBTCKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '미즈호은행 서울지점',         nameEn: 'Mizuho Bank Ltd Seoul Branch',                      swift: 'MHCBKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '모간스탠리은행 서울지점',     nameEn: 'Morgan Stanley Bank International Seoul Branch',    swift: 'MSBKKRSE', city: '서울', category: '외국계은행' },
  { nameKo: 'MUFG은행 서울지점',           nameEn: 'MUFG Bank Ltd Seoul Branch',                        swift: 'BOTKKRSX', city: '서울', category: '외국계은행' },
  { nameKo: '파키스탄국립은행 서울지점',   nameEn: 'National Bank of Pakistan Seoul Branch',            swift: 'NBPAKRSI', city: '서울', category: '외국계은행' },
  { nameKo: 'OCBC 서울지점',               nameEn: 'Oversea-Chinese Banking Corporation Seoul Branch',  swift: 'OCBCKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '소시에테제네랄 서울지점',     nameEn: 'Societe Generale Seoul Branch',                     swift: 'SOGEKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '인도국립은행 서울지점',       nameEn: 'State Bank of India Seoul Branch',                  swift: 'SBINKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '스테이트스트리트은행 서울지점', nameEn: 'State Street Bank and Trust Company Korea Branch', swift: 'SBOSKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '스미토모미쓰이은행 서울지점', nameEn: 'Sumitomo Mitsui Banking Corporation Seoul Branch',  swift: 'SMBCKRSE', city: '서울', category: '외국계은행' },
  { nameKo: 'BNY멜론은행 서울지점',        nameEn: 'The Bank of New York Mellon Seoul Branch',          swift: 'IRVTKRSX', city: '서울', category: '외국계은행' },
  { nameKo: 'HSBC 서울지점',               nameEn: 'HSBC Seoul Branch',                                 swift: 'HSBCKRSE', city: '서울', category: '외국계은행' },
  { nameKo: 'UBAF 서울지점',               nameEn: 'Union de Banques Arabes et Francaises Seoul',       swift: 'UBAFKRSX', city: '서울', category: '외국계은행' },
  { nameKo: 'UBS 서울지점',                nameEn: 'UBS AG Seoul Branch',                               swift: 'CRESKRSE', city: '서울', category: '외국계은행' },
  { nameKo: 'UOB 서울지점',                nameEn: 'United Overseas Bank Seoul Branch',                  swift: 'UOVBKRSE', city: '서울', category: '외국계은행' },
  { nameKo: '웰스파고은행 서울지점',       nameEn: 'Wells Fargo Bank N.A. Seoul Branch',                swift: 'PNBPKRSX', city: '서울', category: '외국계은행' },
  { nameKo: '크레딧아그리콜 서울지점',     nameEn: 'Credit Agricole CIB Seoul Branch',                  swift: 'CRLYKRSE', city: '서울', category: '외국계은행' },
  // ── 증권·자산운용 ─────────────────────────────────────────────
  { nameKo: '애셋플러스자산운용',    nameEn: 'Assetplus Investment Management Co Ltd',              swift: 'APIMKR22', city: '성남', category: '증권·자산운용' },
  { nameKo: '바로투자증권',          nameEn: 'Baro Investment and Securities Co., Ltd.',             swift: 'BRIUKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'BNK증권',               nameEn: 'BNK Securities Co., Ltd.',                            swift: 'BNKSKR22', city: '부산', category: '증권·자산운용' },
  { nameKo: 'BNP파리바증권코리아',   nameEn: 'BNP Paribas Securities Korea Co., Ltd.',              swift: 'BNPAKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '부국증권',              nameEn: 'Bookook Securities Co Ltd',                           swift: 'BOOSKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'BZW증권',               nameEn: 'BZW Securities Ltd.',                                 swift: 'BZSEKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'Celenian자산운용',      nameEn: 'Celenian Asset Management (Korea) Limited',           swift: 'CSAKKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'CGS국제증권 한국지점',  nameEn: 'CGS International Securities HK, Korea Branch',      swift: 'CSKRKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '씨티그룹증권코리아',    nameEn: 'Citigroup Global Markets Korea Securities',           swift: 'KBSSKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'CLSA증권코리아',        nameEn: 'CLSA Securities Korea Ltd.',                          swift: 'CLSAKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '대신자산운용',          nameEn: 'Daishin Asset Management Co., Ltd.',                  swift: 'DAMSKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '대신증권',              nameEn: 'Daishin Securities Co., Ltd.',                        swift: 'DSSCKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '대신증권 (2)',           nameEn: 'Daishin Securities Co., Ltd. (2)',                    swift: 'DSSCKRS3', city: '서울', category: '증권·자산운용' },
  { nameKo: '다이와증권코리아',      nameEn: 'Daiwa Securities Capital Markets Korea',               swift: 'DSCCKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'DB자산운용',            nameEn: 'DB Asset Management Co., Ltd.',                       swift: 'DBMNKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'DB금융투자',            nameEn: 'DB Financial Investment Co., Ltd.',                   swift: 'DSEUKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '도이체증권코리아',      nameEn: 'Deutsche Securities Korea Co.',                        swift: 'DSALKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'DIV자산운용',           nameEn: 'DIV Asset Management Co., Ltd.',                      swift: 'DAMGKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'DS투자증권',            nameEn: 'DS Investment and Securities Co., Ltd.',              swift: 'IVCEKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '유진자산운용',          nameEn: 'Eugene Asset Management Co., Ltd.',                   swift: 'EASMKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '유진투자증권',          nameEn: 'Eugene Investment and Securities',                    swift: 'SEOSKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '에버스트투자증권',      nameEn: 'Evest Investment and Securities Co., Ltd.',            swift: 'ETSIKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '하나자산운용',          nameEn: 'Hana Asset Management Company Ltd',                   swift: 'HANPKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '하나금융투자',          nameEn: 'Hana Financial Investment Co., Ltd.',                 swift: 'HAFVKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '하나증권',              nameEn: 'Hana Securities Co., Ltd.',                           swift: 'HAFVKRS3', city: '서울', category: '증권·자산운용' },
  { nameKo: '한신증권',              nameEn: 'Hanshin Securities Co. Ltd.',                         swift: 'HNSEKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '한화자산운용',          nameEn: 'Hanwha Asset Management Co., Ltd.',                   swift: 'HAATKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '한화투자증권',          nameEn: 'Hanwha Investment and Securities Co., Ltd.',          swift: 'HAITKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '한화투자증권 (2)',       nameEn: 'Hanwha Investment and Securities Co., Ltd. (2)',      swift: 'HNWSKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '한화투자증권 (3)',       nameEn: 'Hanwha Investment and Securities Co., Ltd. (3)',      swift: 'HNWSKRSS', city: '서울', category: '증권·자산운용' },
  { nameKo: '한양증권',              nameEn: 'Hanyang Securities Co. Ltd.',                         swift: 'HSECKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '흥국자산운용',          nameEn: 'Heungkuk Asset Management',                           swift: 'HEANKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '흥국증권',              nameEn: 'Heungkuk Securities Co., Ltd.',                       swift: 'HESTKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '현대자산운용',          nameEn: 'Hyundai Asset Management Co., Ltd.',                  swift: 'HYAMKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '현대인베스트먼트',      nameEn: 'Hyundai Investments Co., Ltd.',                       swift: 'HYUNKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '현대차증권',            nameEn: 'Hyundai Motor Securities Co., Ltd.',                  swift: 'SHHEKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '현대차증권 (2)',         nameEn: 'Hyundai Motor Securities Co., Ltd. (2)',              swift: 'HYMEKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: 'IBK자산운용',           nameEn: 'IBK Asset Management Co., Ltd.',                      swift: 'IBKMKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'IBK투자증권',           nameEn: 'IBK Securities Co., Ltd.',                            swift: 'IBKSKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'IBK투자증권 (2)',        nameEn: 'IBK Securities Co., Ltd. (2)',                        swift: 'IBKSKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: 'IGIS자산운용',          nameEn: 'IGIS Asset Management Co., Ltd.',                     swift: 'IGAAKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'iM증권',                nameEn: 'IM Securities Co., Ltd.',                             swift: 'HVSCKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'ING은행 서울증권',      nameEn: 'ING Bank N.V. Seoul Securities',                      swift: 'INGBKRSS', city: '서울', category: '증권·자산운용' },
  { nameKo: 'JP모간증권 서울지점',   nameEn: 'J.P. Morgan Securities (Far East) Ltd Seoul',         swift: 'CHASKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: 'JP모간증권 (2)',         nameEn: 'J.P.Morgan Securities(Far East) Ltd. Seoul (2)',      swift: 'JMSAKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'Kardian자산운용',       nameEn: 'Kardian Asset Management Co., Ltd.',                  swift: 'EAMKKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'KB자산운용',            nameEn: 'KB Asset Management',                                 swift: 'KBAMKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'KB증권',                nameEn: 'KB Securities Co., Ltd.',                             swift: 'HYSEKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '키움자산운용',          nameEn: 'Kiwoom Asset Management Co., Ltd.',                   swift: 'KIWMKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '키움증권',              nameEn: 'Kiwoom Securities Co., Ltd.',                         swift: 'KIWCKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '키움증권 (2)',           nameEn: 'Kiwoom Securities Co., Ltd. (2)',                     swift: 'KIWCKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '코리아펀드파트너스',    nameEn: 'Korea Fund Partners',                                 swift: 'MRFSKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '한국투자증권',          nameEn: 'Korea Investment and Securities Co., Ltd.',           swift: 'DOSUKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '한국투자증권 (2)',       nameEn: 'Korea Investment and Securities Co., Ltd. (2)',       swift: 'KISEKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '한국투자신탁운용',      nameEn: 'Korea Investment Trust Management Co.',               swift: 'KITNKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'KTB자산운용',           nameEn: 'KTB Asset Management Co., Ltd.',                      swift: 'KTAMKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'KTB투자증권',           nameEn: 'KTB Investment and Securities Co., Ltd.',             swift: 'BRNAKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '교보악사투자운용',      nameEn: 'Kyobo AXA Investment Managers Co., Ltd.',             swift: 'KAIGKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '교보증권',              nameEn: 'Kyobo Securities Co., Ltd.',                          swift: 'KYOBKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '리딩투자증권',          nameEn: 'Leading Investment and Securities Co., Ltd.',         swift: 'LISCKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '메리츠자산운용',        nameEn: 'Meritz Asset Management Co., Ltd.',                   swift: 'MEEMKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '메리츠증권',            nameEn: 'Meritz Securities',                                   swift: 'HANEKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '메리츠증권 (2)',         nameEn: 'Meritz Securities Co., Ltd. (2)',                     swift: 'KFBCKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '메릴린치 서울지점',     nameEn: 'Merrill Lynch International Seoul Branch',            swift: 'MLCOKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '메릴린치 서울지점 (2)', nameEn: 'Merrill Lynch International LLC Seoul Branch',        swift: 'MLKRKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '메릴린치 서울지점 (3)', nameEn: 'Merrill Lynch International Seoul Office',            swift: 'MLKRKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '미래에셋자산운용',      nameEn: 'Mirae Asset Asset Management Co., Ltd.',              swift: 'MALSKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '미래에셋자산운용 (2)',   nameEn: 'Mirae Asset Asset Management Co., Ltd. (2)',          swift: 'MAONKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '미래에셋자산운용 (3)',   nameEn: 'Mirae Asset Asset Management Co., Ltd. (3)',          swift: 'MAVAKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '미래에셋증권',          nameEn: 'Mirae Asset Securities Co., Ltd.',                    swift: 'MIAEKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '미래에셋증권 (2)',       nameEn: 'Mirae Asset Securities Co., Ltd. (2)',                swift: 'MIAEKR21', city: '서울', category: '증권·자산운용' },
  { nameKo: '모간스탠리 서울지점',   nameEn: 'Morgan Stanley and Co. International PLC Seoul',      swift: 'MSNYKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '모간스탠리 서울지점 (2)', nameEn: 'Morgan Stanley and Co. International PLC Seoul (2)', swift: 'MSKRKRSX', city: '서울', category: '증권·자산운용' },
  { nameKo: '멀티에셋글로벌',        nameEn: 'Multi Asset Global Investments Co., Ltd.',            swift: 'KDAMKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'MUST자산운용',          nameEn: 'Must Asset Management Inc.',                          swift: 'MUAGKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'NH아문디자산운용',      nameEn: 'NH Amundi Asset Management Co., Ltd.',                swift: 'NHAMKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'NH아문디자산운용 (2)',   nameEn: 'NH-Amundi Asset Management Co., Ltd. (2)',            swift: 'AMEGKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: 'NH투자증권',            nameEn: 'NH Investment and Securities Co., Ltd.',              swift: 'LUSEKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'NH투자증권 (2)',         nameEn: 'NH Investment and Securities Co., Ltd. (2)',          swift: 'HNISKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'NH투자증권 (3)',         nameEn: 'NH Investment and Securities Co., Ltd. (3)',          swift: 'WISHKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '노무라금융투자',        nameEn: 'Nomura Financial Investment (Korea) Co., Ltd.',       swift: 'NFIKKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '쿼드투자운용',          nameEn: 'Quad Investment Management Corporation',              swift: 'QIMCKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '삼성액티브자산운용',    nameEn: 'Samsung Active Asset Management Co., Ltd.',           swift: 'SECTKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '삼성자산운용',          nameEn: 'Samsung Asset Management Co., Ltd.',                  swift: 'SITAKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '삼성자산운용 (2)',       nameEn: 'Samsung Asset Management Co., Ltd. (2)',              swift: 'SITAKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '삼성증권',              nameEn: 'Samsung Securities Co., Ltd.',                        swift: 'SAMCKRSL', city: '서울', category: '증권·자산운용' },
  { nameKo: '삼성증권 (2)',           nameEn: 'Samsung Securities Co., Ltd. (2)',                    swift: 'SAMCKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'SG증권코리아',          nameEn: 'SG Securities Korea Co., Ltd.',                       swift: 'SGSEKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'SG증권코리아 (2)',       nameEn: 'SG Securities Korea Co., Ltd. (2)',                   swift: 'SGSEKRSL', city: '서울', category: '증권·자산운용' },
  { nameKo: '신한자산운용',          nameEn: 'Shinhan Asset Management Co., Ltd.',                  swift: 'SSATKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '신한BNP파리바자산운용', nameEn: 'Shinhan BNP Paribas Asset Management Co., Ltd.',     swift: 'SBPAKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '신한투자증권',          nameEn: 'Shinhan Securities Co., Ltd.',                        swift: 'SSISKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '신한투자증권 (2)',       nameEn: 'Shinhan Securities Co., Ltd. (2)',                    swift: 'SSISKRSS', city: '서울', category: '증권·자산운용' },
  { nameKo: '신한증권 (구)',          nameEn: 'Shin Han Securities Co. Ltd.',                        swift: 'SHHSKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '신영증권',              nameEn: 'Shinyoung Securities Co. Ltd.',                       swift: 'SHSEKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'SK증권',                nameEn: 'SK Securities',                                       swift: 'SKSEKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '스마일게이트자산운용',  nameEn: 'Smilegate Asset Management Inc.',                     swift: 'SMIEKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'SC증권코리아',          nameEn: 'Standard Chartered Securities Korea Limited',         swift: 'SCKRKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '타우러스자산운용',      nameEn: 'Taurus Asset Management Co., Ltd.',                   swift: 'TAUSKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'TI자산운용',            nameEn: 'TI Asset Management Co., Ltd.',                       swift: 'TIAEKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '타임폴리오자산운용',    nameEn: 'Timefolio Asset Management Co., Ltd.',                swift: 'TMCOKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: '동양투자증권',          nameEn: 'Tong Yang Investment Bank',                           swift: 'TYSEKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '트러스톤자산운용',      nameEn: 'Truston Asset Management Co., Ltd.',                  swift: 'TRTMKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'UBS증권 서울지점',      nameEn: 'UBS Securities Pte. Ltd. Seoul Branch',               swift: 'WAREKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'VI자산운용',            nameEn: 'VI Asset Management Korea Co., Ltd.',                 swift: 'VIAEKRS2', city: '서울', category: '증권·자산운용' },
  { nameKo: 'VIA자산운용',           nameEn: 'VIA Asset Management Co., Ltd.',                      swift: 'ASNMKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'W자산운용',             nameEn: 'W Asset Management Co., Ltd.',                        swift: 'ASGTKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: 'W.I.카 서울지점',       nameEn: 'W.I. Carr (Far East) Limited',                        swift: 'WICAKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '우리자산운용',          nameEn: 'Woori Asset Management Co., Ltd.',                    swift: 'TOYIKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '우리자산운용 (2)',       nameEn: 'Woori Asset Management Co., Ltd. (2)',                swift: 'TYAMKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '우리자산운용 (3)',       nameEn: 'Woori Asset Management Co., Ltd. (3)',                swift: 'TYITKRS1', city: '서울', category: '증권·자산운용' },
  { nameKo: '우리투자증권',          nameEn: 'Woori Investment Securities Co. Ltd.',                swift: 'KHMBKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '유안타증권코리아',      nameEn: 'Yuanta Securities Korea Co., Ltd.',                   swift: 'TYMBKRSE', city: '서울', category: '증권·자산운용' },
  { nameKo: '유리자산운용',          nameEn: 'Yurie Asset Management Inc.',                         swift: 'YUAMKRS2', city: '서울', category: '증권·자산운용' },
  // ── 기타 금융·비금융기관 ─────────────────────────────────────
  { nameKo: '아우디폭스바겐코리아',  nameEn: 'Audi Volkswagen Korea Ltd.',                  swift: 'AUVKKRS1', city: '서울',   category: '기타' },
  { nameKo: 'BAT코리아',             nameEn: 'British American Tobacco Korea',              swift: 'BATSKRS1', city: '서울',   category: '기타' },
  { nameKo: 'BAT코리아 제조',        nameEn: 'British American Tobacco Korea Mfg.',         swift: 'BATSKR21', city: '사천',   category: '기타' },
  { nameKo: '제일기획',              nameEn: 'Cheil Worldwide, Inc.',                       swift: 'CIWWKRSE', city: '서울',   category: '기타' },
  { nameKo: 'CI보증',                nameEn: 'CI Guarantee',                               swift: 'PMCFKRSE', city: '서울',   category: '기타' },
  { nameKo: 'CJ제일제당',            nameEn: 'CJ Cheiljedang Corporation',                  swift: 'CJCCKRSS', city: '서울',   category: '기타' },
  { nameKo: '건설보증협동조합',      nameEn: 'Construction Guarantee Cooperative',          swift: 'KCGCKRSE', city: '서울',   category: '기타' },
  { nameKo: '코르부스',              nameEn: 'Corvus Co., Ltd.',                            swift: 'CRUVKRS1', city: '서울',   category: '기타' },
  { nameKo: 'E9PAY',                 nameEn: 'E9PAY Co. Ltd',                               swift: 'NINPKRSE', city: '서울',   category: '기타' },
  { nameKo: '엔지니어링보증보험',    nameEn: 'Engineering Guarantee Insurance',             swift: 'ENGUKRSE', city: '서울',   category: '기타' },
  { nameKo: '녹색기후기금',          nameEn: 'Green Climate Fund',                          swift: 'GCLFKR22', city: '인천',   category: '기타' },
  { nameKo: '한진물류',              nameEn: 'Hanjin Logistics Corporation',                swift: 'HLCRKRSE', city: '서울',   category: '기타' },
  { nameKo: '한화생명',              nameEn: 'Hanwha Life Insurance',                       swift: 'HWLIKRSE', city: '서울',   category: '기타' },
  { nameKo: '한화비전',              nameEn: 'Hanwha Vision Co., Ltd.',                     swift: 'SSTWKR22', city: '성남',   category: '기타' },
  { nameKo: 'HP코리아',              nameEn: 'Hewlett-Packard Korea Ltd.',                  swift: 'HEKOKRS1', city: '서울',   category: '기타' },
  { nameKo: 'HL만도',                nameEn: 'HL Mando Corporation',                        swift: 'MCRAKR2K', city: '성남',   category: '기타' },
  { nameKo: '호텔롯데 면세점',       nameEn: 'Hotel Lotte Co., Ltd. (Duty Free)',           swift: 'LDFSKRSE', city: '서울',   category: '기타' },
  { nameKo: '하이브',                nameEn: 'HYBE Co., Ltd.',                              swift: 'HYBEKRSE', city: '서울',   category: '기타' },
  { nameKo: '현대건설',              nameEn: 'Hyundai Engineering and Construction Co.',    swift: 'HEGCKRSE', city: '서울',   category: '기타' },
  { nameKo: '현대엔지니어링',        nameEn: 'Hyundai Engineering Co., Ltd.',               swift: 'HYECKRSE', city: '서울',   category: '기타' },
  { nameKo: '현대글로비스',          nameEn: 'Hyundai Glovis Co. Ltd.',                     swift: 'HGLOKRSE', city: '서울',   category: '기타' },
  { nameKo: '현대모비스',            nameEn: 'Hyundai Mobis, Co., Ltd.',                    swift: 'HYMOKRSE', city: '서울',   category: '기타' },
  { nameKo: '현대제철',              nameEn: 'Hyundai Steel',                               swift: 'HYSCKR22', city: '인천',   category: '기타' },
  { nameKo: '한국거래소',            nameEn: 'Korea Exchange',                              swift: 'KORXKR21', city: '부산',   category: '기타' },
  { nameKo: '건설금융공사',          nameEn: 'Korea Finance for Construction',              swift: 'KSCFKRSE', city: '서울',   category: '기타' },
  { nameKo: '금융결제원',            nameEn: 'Korea Financial Telecommunications and Clearing Institute', swift: 'KFTCKRS1', city: '서울', category: '기타' },
  { nameKo: '한국투자공사',          nameEn: 'Korea Investment Corporation',               swift: 'KOICKRSE', city: '서울',   category: '기타' },
  { nameKo: '한국예탁결제원',        nameEn: 'Korea Securities Depository',                swift: 'KSDCKRSE', city: '서울',   category: '기타' },
  { nameKo: '한국증권금융',          nameEn: 'Korea Securities Finance Corporation',       swift: 'KOSFKRS1', city: '서울',   category: '기타' },
  { nameKo: '한국증권금융 (2)',       nameEn: 'Korea Securities Finance Corporation (2)',   swift: 'KOSFKRSK', city: '서울',   category: '기타' },
  { nameKo: 'KT&G',                  nameEn: 'KT and G Corporation',                       swift: 'KTGCKRSE', city: '서울',   category: '기타' },
  { nameKo: 'KOH제3자산유동화',      nameEn: 'KOH Third Asset Securitization',             swift: 'KTASKRS1', city: '서울',   category: '기타' },
  { nameKo: '교보생명',              nameEn: 'Kyobo Life Insurance Co., Ltd.',             swift: 'KYBOKRSE', city: '서울',   category: '기타' },
  { nameKo: 'LG화학',                nameEn: 'LG Chem, Ltd.',                              swift: 'CEMMKRSE', city: '서울',   category: '기타' },
  { nameKo: 'LG CNS',                nameEn: 'LG CNS Co., Ltd.',                           swift: 'LGCNKRS1', city: '서울',   category: '기타' },
  { nameKo: 'LG디스플레이',          nameEn: 'LG Display',                                 swift: 'LGDTKRSE', city: '서울',   category: '기타' },
  { nameKo: 'LG전자',                nameEn: 'LG Electronics Inc.',                        swift: 'LGETKRSE', city: '서울',   category: '기타' },
  { nameKo: '롯데케미칼',            nameEn: 'Lotte Chemical Corporation',                 swift: 'LTCHKRSE', city: '서울',   category: '기타' },
  { nameKo: '롯데에너지머티리얼즈',  nameEn: 'Lotte Energy Materials Corporation',         swift: 'LEACKRSE', city: '서울',   category: '기타' },
  { nameKo: '메르세데스벤츠파이낸셜코리아', nameEn: 'Mercedes-Benz Financial Services Korea', swift: 'MBFKKRSE', city: '서울', category: '기타' },
  { nameKo: '메르세데스벤츠코리아',  nameEn: 'Mercedes-Benz Korea Limited',               swift: 'MBKRKRSE', city: '서울',   category: '기타' },
  { nameKo: '모인',                  nameEn: 'Moin, Inc.',                                 swift: 'MNNNKRS2', city: '서울',   category: '기타' },
  { nameKo: 'MTI코퍼레이션',         nameEn: 'MTI Corporation',                            swift: 'MTIRKR22', city: '안산',   category: '기타' },
  { nameKo: '농협중앙회',            nameEn: 'National Agricultural Cooperative Federation', swift: 'NACEKRS1', city: '서울', category: '기타' },
  { nameKo: '국민연금공단',          nameEn: 'National Pension Service',                  swift: 'NPSFKRSJ', city: '전주',   category: '기타' },
  { nameKo: '국민연금 투자운용',     nameEn: 'National Pension Service Investment Management', swift: 'NPSFKRS1', city: '서울', category: '기타' },
  { nameKo: '나이키 스포츠 코리아',  nameEn: 'Nike Sports Korea Co., Ltd.',               swift: 'NIKEKRS1', city: '서울',   category: '기타' },
  { nameKo: '오스템임플란트',        nameEn: 'Osstem Implant Co., Ltd.',                  swift: 'OSIMKRSE', city: '서울',   category: '기타' },
  { nameKo: 'POSCO홀딩스',           nameEn: 'POSCO Holdings Inc.',                        swift: 'PSCCKRSE', city: '서울',   category: '기타' },
  { nameKo: '우체국 본부',           nameEn: 'Postal Business Headquarters',              swift: 'KOPOKRS1', city: '서울',   category: '기타' },
  { nameKo: 'BAT코리아 (로스만스)',  nameEn: 'Rothmans Far East B.V. Korea',               swift: 'BATSKR31', city: '서울',   category: '기타' },
  { nameKo: '삼성C&T',               nameEn: 'Samsung C and T Corporation',               swift: 'SCNTKRSE', city: '서울',   category: '기타' },
  { nameKo: '삼성C&T 무역부문',      nameEn: 'Samsung C and T Corporation Trading',       swift: 'SCNTKRST', city: '서울',   category: '기타' },
  { nameKo: '삼성전기',              nameEn: 'Samsung Electro-Mechanics Co., Ltd.',        swift: 'SEMTKR22', city: '수원',   category: '기타' },
  { nameKo: '삼성전자',              nameEn: 'Samsung Electronics Co., Ltd.',              swift: 'SECTKRSE', city: '수원',   category: '기타' },
  { nameKo: '삼성엔지니어링',        nameEn: 'Samsung Engineering Co., Ltd.',              swift: 'SMSGKRSE', city: '서울',   category: '기타' },
  { nameKo: '삼성화재',              nameEn: 'Samsung Fire and Marine Insurance Co., Ltd.', swift: 'SFMIKRSE', city: '서울',  category: '기타' },
  { nameKo: '삼성중공업',            nameEn: 'Samsung Heavy Industries Co., Ltd.',         swift: 'SSHIKRSE', city: '성남',   category: '기타' },
  { nameKo: '삼성생명',              nameEn: 'Samsung Life Insurance Co., Ltd.',           swift: 'SSLIKRSE', city: '서울',   category: '기타' },
  { nameKo: '삼성SDI',               nameEn: 'Samsung SDI Co., Ltd.',                      swift: 'SSDIKR22', city: '용인',   category: '기타' },
  { nameKo: '삼성SDS',               nameEn: 'Samsung SDS Co., Ltd.',                      swift: 'SSDSKRSE', city: '서울',   category: '기타' },
  { nameKo: '삼성웰스토리',          nameEn: 'Samsung Welstory Incorporated',              swift: 'SWEIKRSE', city: '서울',   category: '기타' },
  { nameKo: '센트비',                nameEn: 'Sentbe Inc.',                                swift: 'SNTBKRS2', city: '서울',   category: '기타' },
  { nameKo: '서울보증보험',          nameEn: 'Seoul Guarantee Insurance Company',          swift: 'KSGIKRSE', city: '서울',   category: '기타' },
  { nameKo: '서브원',                nameEn: 'Serveone Co., Ltd.',                         swift: 'SRVEKRSE', city: '서울',   category: '기타' },
  { nameKo: 'SK바이오텍',            nameEn: 'SK Biotek',                                  swift: 'BIOKKR22', city: '대전',   category: '기타' },
  { nameKo: 'SK이노베이션',          nameEn: 'SK Innovation Co., Ltd.',                    swift: 'IOCOKRSE', city: '서울',   category: '기타' },
  { nameKo: '타노스',                nameEn: 'Thanos Co., Ltd.',                           swift: 'THAOKRS1', city: '서울',   category: '기타' },
  { nameKo: '트래블월렛',            nameEn: 'Travel Wallet Co., Ltd.',                    swift: 'TRWLKRS2', city: '서울',   category: '기타' },
  { nameKo: 'U핀테크허브',           nameEn: 'U Fintech Hub Inc.',                         swift: 'FIHBKRS2', city: '서울',   category: '기타' },
  { nameKo: '와이어바알리',          nameEn: 'Wirebarley Corporation',                     swift: 'WIOOKRS2', city: '서울',   category: '기타' },
]
